### ISSUE TITLE
mix

### ISSUE THREAD

**Issue by BigManzai** [djphil/osmw#1]
Database.sql Table structure for table `config` OK
Database.sql write data for table `config` ERROR
crash
------
firstname = super
lastname  = admin
password  = password
is not correct

correct
firstname = Super
lastname  = Admin
password  = password
-----
Language not work

**Comment by djphil** [comment]
Fixed in 6ec7dcba6ebe7f86d03808df2a2981ef3c927804. Thanks for reporting.
